services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
